# Generated by Django 5.1 on 2024-08-21 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban', models.CharField(max_length=24)),
                ('balance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Trasaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField()),
                ('amount', models.FloatField()),
                ('balance', models.FloatField()),
                ('type', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transfers.account')),
            ],
        ),
    ]
