# Generated by Django 5.1 on 2024-08-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='temp_field',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
