# Generated by Django 5.1 on 2024-08-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0002_account_temp_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='temp_field',
        ),
        migrations.AlterField(
            model_name='trasaction',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='trasaction',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
    ]
